### ISSUE TITLE
Add safeguards for arbitrary code execution

### ISSUE THREAD

**Issue by GGyll** [GGyll/condo_gpt#3]
in `main.py` we are executing any python code returned by the LLM in exec(code), but if the LLM returns malicious code it can damage our system!

See if there are any safeguards we can put out to prevent that.

**Comment by GGyll** [comment]
One way is to run the code in a sandboxed environment, so it does not interact with the host system. Another approach is to check the LLM content by another Model before executing it, to see if any malicious code is present or not.

Open to other approaches as well!

**Comment by LuciAkirami** [comment]
@GGyll , as stated in the video comments, we can also use regex to detect if any python libraries may potentially run any system commands. Can I work on this issue?

**Comment by GGyll** [comment]
Yes go ahead, this sounds good

**Comment by LuciAkirami** [comment]
Cool. Can you then assign this issue to me, so that I can get started

**Comment by LuciAkirami** [comment]
Hey @GGyll , I have opened a PR to solve this issue. Can you review it?

**Comment by LuciAkirami** [comment]
#7

**Comment by GGyll** [comment]
will review later this week
